version: '3'
services:
  node_app:
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/usr/node/app
      - /usr/node/app/node_modules
    restart: unless-stopped

