CREATE OR REPLACE PROCEDURE INSERT_COMMENT(COMMENT IN VARCHAR2,CONT_BY IN NUMBER, TYPE IN VARCHAR2, TYPED_ID IN NUMBER)
IS
    COMMENT_ID NUMBER;
BEGIN
    IF TYPE = 'QUESTION' OR TYPE = 'ANSWER' OR TYPE='ARTICLE' THEN
        INSERT INTO COMMENTS (TEXT, CONTRIBUTED_BY ) VALUES (COMMENT, CONT_BY) RETURNING ID INTO COMMENT_ID;
        IF TYPE = 'QUESTION' THEN
            INSERT INTO QUESTION_COMMENT (QUESTION_ID, COMMENT_ID) VALUES (TYPED_ID, COMMENT_ID);
        ELSIF TYPE = 'ARTICLE' THEN
            INSERT INTO ARTICLE_COMMENT (ARTICLE_ID, COMMENT_ID) VALUES (TYPED_ID, COMMENT_ID);
        ELSIF TYPE = 'ANSWER' THEN
            INSERT INTO ANSWER_COMMENT (ANSWER_ID, COMMENT_ID) VALUES (TYPED_ID, COMMENT_ID);
        END IF;
    END IF;
END;
/

---REACT PROCEDURES;
CREATE OR REPLACE PROCEDURE REACT_QUESTION (QID IN NUMBER,UID IN NUMBER, REACT_ IN VARCHAR2) IS 
	CNT NUMBER;
BEGIN 
	SELECT COUNT(*) INTO CNT  
	FROM QUESTION_REACT 
	WHERE QUESTION_ID=QID AND REACTED_BY=UID;
		
	IF CNT=0 THEN 
		INSERT INTO QUESTION_REACT (QUESTION_ID,REACTED_BY,REACT) VALUES (QID,UID,REACT_);
	ELSE 
		UPDATE QUESTION_REACT SET REACT=REACT_ WHERE QUESTION_ID=QID AND REACTED_BY=UID ;
	END IF;
END ;
/
CREATE OR REPLACE PROCEDURE REACT_ARTICLE (AID IN NUMBER,UID IN NUMBER, REACT_ IN VARCHAR2) IS 
	CNT NUMBER;
BEGIN 
	SELECT COUNT(*) INTO CNT  
	FROM ARTICLE_REACT 
	WHERE ARTICLE_ID=AID AND REACTED_BY=UID;
		
	IF CNT=0 THEN 
		INSERT INTO ARTICLE_REACT (ARTICLE_ID,REACTED_BY,REACT) VALUES (AID,UID,REACT_);
	ELSE 
		UPDATE ARTICLE_REACT SET REACT=REACT_ WHERE ARTICLE_ID=AID AND REACTED_BY=UID ;
	END IF;
END ;
/

CREATE OR REPLACE PROCEDURE REACT_ANSWER (AID IN NUMBER,UID IN NUMBER, REACT_ IN VARCHAR2) IS 
	CNT NUMBER;
BEGIN 
	SELECT COUNT(*) INTO CNT  
	FROM ANSWER_REACT 
	WHERE ANSWER_ID=AID AND REACTED_BY=UID;
		
	IF CNT=0 THEN 
		INSERT INTO ANSWER_REACT (ANSWER_ID,REACTED_BY,REACT) VALUES (AID,UID,REACT_);
	ELSE 
		UPDATE ANSWER_REACT SET REACT=REACT_ WHERE ANSWER_ID=AID AND REACTED_BY=UID ;
	END IF;
END ;
/