CREATE OR REPLACE PROCEDURE INSERT_COMMENT(COMMENT_TEXT IN VARCHAR2,CONT_BY IN NUMBER, COMMENT_OF IN VARCHAR2, TYPED_ID IN NUMBER)
IS
    COMMENT_ID NUMBER;
	TYPE_CONT_BY NUMBER;
	ANS_QUS_ID NUMBER; 
	TYPE_ VARCHAR2(30);
BEGIN
	TYPE_ := UPPER(COMMENT_OF);
    IF TYPE_ = 'QUESTION' OR TYPE_ = 'ANSWER' OR TYPE_ ='ARTICLE' THEN
        INSERT INTO COMMENTS (TEXT, CONTRIBUTED_BY ) VALUES (COMMENT_TEXT, CONT_BY) RETURNING ID INTO COMMENT_ID;
        IF TYPE_ = 'QUESTION' THEN
            INSERT INTO QUESTION_COMMENT (QUESTION_ID, COMMENT_ID) VALUES (TYPED_ID, COMMENT_ID);
		
			SELECT CONTRIBUTED_BY INTO TYPE_CONT_BY
			FROM QUESTION 
			WHERE ID=TYPED_ID;
			
			INSERT INTO NOTIFICATION (
				PROFILE_ID,
				LINK,
				MESSAGE
			)
			VALUES (
				TYPE_CONT_BY,
				'/question/' || TYPED_ID,
				(SELECT (FIRST_NAME||' '||LAST_NAME) FROM PROFILE WHERE ID = CONT_BY) ||' commented on your question.'
			);

		ELSIF TYPE_ = 'ARTICLE' THEN
			INSERT INTO ARTICLE_COMMENT (ARTICLE_ID, COMMENT_ID) VALUES (TYPED_ID, COMMENT_ID);

			SELECT CONTRIBUTED_BY INTO TYPE_CONT_BY
			FROM ARTICLE 
			WHERE ID=TYPED_ID;
			
			INSERT INTO NOTIFICATION (
				PROFILE_ID,
				LINK,
				MESSAGE
			)
			VALUES (
				TYPE_CONT_BY,
				'/article/' || TYPED_ID,
				(SELECT (FIRST_NAME||' '||LAST_NAME) FROM PROFILE WHERE ID=CONT_BY) ||' commented on your article.'
			);
		ELSIF TYPE_ = 'ANSWER' THEN
			INSERT INTO ANSWER_COMMENT (ANSWER_ID, COMMENT_ID) VALUES (TYPED_ID, COMMENT_ID);

			SELECT CONTRIBUTED_BY,QUESTION_ID INTO TYPE_CONT_BY,ANS_QUS_ID
			FROM ANSWER
			WHERE ID=TYPED_ID;

			INSERT INTO NOTIFICATION (
				PROFILE_ID,
				LINK,
				MESSAGE
			)
			VALUES (
				TYPE_CONT_BY,
				'/question/' || ANS_QUS_ID,
				(SELECT (FIRST_NAME||' '||LAST_NAME) FROM PROFILE WHERE ID=CONT_BY) ||' commented on your answer.'
			);
		END IF;
    END IF;
END;
/


---REACT PROCEDURES;
CREATE OR REPLACE PROCEDURE REACT_QUESTION (QID IN NUMBER,UID IN NUMBER, REACT_ IN VARCHAR2) IS 
	CNT NUMBER;
BEGIN 
	SELECT COUNT(*) INTO CNT  
	FROM QUESTION_REACT 
	WHERE QUESTION_ID=QID AND REACTED_BY=UID;
		
	IF CNT=0 THEN 
		INSERT INTO QUESTION_REACT (QUESTION_ID,REACTED_BY,REACT) VALUES (QID,UID,REACT_);
	ELSE 
		UPDATE QUESTION_REACT SET REACT=REACT_ WHERE QUESTION_ID=QID AND REACTED_BY=UID ;
	END IF;
END ;
/
CREATE OR REPLACE PROCEDURE REACT_ARTICLE (AID IN NUMBER,UID IN NUMBER, REACT_ IN VARCHAR2) IS 
	CNT NUMBER;
BEGIN 
	SELECT COUNT(*) INTO CNT  
	FROM ARTICLE_REACT 
	WHERE ARTICLE_ID=AID AND REACTED_BY=UID;
		
	IF CNT=0 THEN 
		INSERT INTO ARTICLE_REACT (ARTICLE_ID,REACTED_BY,REACT) VALUES (AID,UID,REACT_);
	ELSE 
		UPDATE ARTICLE_REACT SET REACT=REACT_ WHERE ARTICLE_ID=AID AND REACTED_BY=UID ;
	END IF;
END ;
/

CREATE OR REPLACE PROCEDURE REACT_ANSWER (AID IN NUMBER,UID IN NUMBER, REACT_ IN VARCHAR2) IS 
	CNT NUMBER;
BEGIN 
	SELECT COUNT(*) INTO CNT  
	FROM ANSWER_REACT 
	WHERE ANSWER_ID=AID AND REACTED_BY=UID;
		
	IF CNT=0 THEN 
		INSERT INTO ANSWER_REACT (ANSWER_ID,REACTED_BY,REACT) VALUES (AID,UID,REACT_);
	ELSE 
		UPDATE ANSWER_REACT SET REACT=REACT_ WHERE ANSWER_ID=AID AND REACTED_BY=UID ;
	END IF;
END ;
/